# Generated by Django 2.0.3 on 2018-03-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='标题')),
                ('topic', models.CharField(max_length=20, verbose_name='主题')),
                ('text', models.TextField(verbose_name='博文')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
