# Generated by Django 2.0.3 on 2018-03-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtext',
            old_name='titel',
            new_name='title',
        ),
    ]
