# Generated by Django 2.0.3 on 2018-03-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180314_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtext',
            options={'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
        migrations.AddField(
            model_name='blogtext',
            name='type',
            field=models.CharField(choices=[('original', '原创'), ('reproduce', '转载')], default='original', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='blogtext',
            name='time',
            field=models.DateTimeField(verbose_name='编辑时间'),
        ),
    ]
