# Generated by Django 2.0.3 on 2018-03-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180314_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtext',
            name='type',
            field=models.CharField(choices=[('原创', 'original'), ('转载', 'reproduce')], default='原创', max_length=20, verbose_name='类型'),
        ),
    ]
