# Generated by Django 2.0.3 on 2018-03-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180314_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtext',
            name='type',
            field=models.CharField(choices=[('原创', '原创'), ('转载', '转载')], default='原创', max_length=20, verbose_name='类型'),
        ),
    ]
