# Generated by Django 2.0.3 on 2018-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180314_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='主题')),
                ('text', models.CharField(max_length=200, verbose_name='内容')),
                ('img', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
