# Generated by Django 2.0.3 on 2018-03-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': '简介', 'verbose_name_plural': '简介'},
        ),
    ]
