# Generated by Django 2.0.3 on 2018-03-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180327_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtext',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.ArticleCatagory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='blogtext',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.ArticleTag', verbose_name='标签'),
        ),
    ]
