# Generated by Django 2.0.3 on 2018-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180327_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtext',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogtext',
            name='tags',
            field=models.ManyToManyField(to='index.ArticleTag', verbose_name='标签'),
        ),
    ]
