# Generated by Django 2.0.3 on 2018-03-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20180327_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtext',
            name='tags',
            field=models.ManyToManyField(to='index.ArticleTag', verbose_name='标签'),
        ),
        migrations.AlterModelTable(
            name='articletag',
            table='tag',
        ),
    ]
