# Generated by Django 2.0.3 on 2018-03-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180327_1928'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articletag',
            table=None,
        ),
    ]
